pub(crate) struct Builtin {
    pub name: &'static str,
    pub hook: &'static str,
    pub description: &'static str,
    pub script: &'static str,
}

pub(crate) const ALL: &[Builtin] = &[
    Builtin {
        name: "conventional-commits",
        hook: "commit-msg",
        description: "Validates Conventional Commits format",
        script: CONVENTIONAL_COMMITS,
    },
    Builtin {
        name: "no-trailers",
        hook: "commit-msg",
        description: "Rejects commit messages carrying AI attribution trailers",
        script: NO_TRAILERS,
    },
    Builtin {
        name: "no-secrets",
        hook: "pre-commit",
        description: "Detects common secret patterns in staged changes",
        script: NO_SECRETS,
    },
    Builtin {
        name: "branch-naming",
        hook: "pre-commit",
        description: "Validates branch name matches convention",
        script: BRANCH_NAMING,
    },
];

pub(crate) fn get(name: &str) -> Option<&'static Builtin> {
    ALL.iter().find(|b| b.name == name)
}

const CONVENTIONAL_COMMITS: &str = r#"#!/bin/sh
commit_msg=$(cat "$1")
pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,}'
if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "ERROR: Commit message does not follow Conventional Commits format."
  echo "Expected: <type>(<scope>): <description>"
  echo "Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
  exit 1
fi
"#;

/// Known AI vendor no-reply addresses that mark an autogenerated attribution
/// trailer (e.g. `Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>`).
/// Add a vendor here, and keep the `vendor_addresses` pattern inside
/// `NO_TRAILERS` in sync — `no_trailers_script_matches_every_known_vendor`
/// in the tests below enforces that. Only read by tests, hence the allow.
#[allow(dead_code)]
pub(crate) const AI_VENDOR_NOREPLY_ADDRESSES: &[&str] = &["noreply@anthropic.com"];

const NO_TRAILERS: &str = r#"#!/bin/sh
# Rejects commit messages carrying AI attribution trailers: a Co-Authored-By,
# Assisted-By or AI-Assisted-By line naming a known AI vendor no-reply
# address, a Claude-Session line, or a "Generated with" line. Genuine human
# Co-Authored-By trailers are left alone.
msg_file="$1"
vendor_addresses='noreply@anthropic\.com'
pattern="^(Co-Authored-By|Assisted-By|AI-Assisted-By):.*(${vendor_addresses})|^Claude-Session:|Generated with"

matches=$(grep -niE "$pattern" "$msg_file")
if [ -n "$matches" ]; then
  echo "ERROR: commit message contains an AI attribution trailer:"
  echo "$matches" | sed 's/^/  /'
  echo ""
  echo "Remove the line(s) above and commit again."
  echo "Human co-authorship is fine: only known AI vendor no-reply addresses (e.g. noreply@anthropic.com) are rejected."
  exit 1
fi
"#;

const NO_SECRETS: &str = r#"#!/bin/sh
# Detects common secret patterns. Not exhaustive — use dedicated tools for production.
patterns='(AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{35}|ghp_[0-9A-Za-z]{36}|sk-[0-9A-Za-z]{48}|password\s*=\s*["'"'"'][^"'"'"']{8,})'
if git diff --cached --diff-filter=ACM | grep -qE "$patterns"; then
  echo "ERROR: Possible secret detected in staged changes."
  echo "Review your changes and remove any credentials before committing."
  exit 1
fi
"#;

const BRANCH_NAMING: &str = r#"#!/bin/sh
branch=$(git symbolic-ref --short HEAD)
pattern='^(main|master|develop|release/.+|hotfix/.+|feat/.+|feature/.+|fix/.+|chore/.+)$'
if ! echo "$branch" | grep -qE "$pattern"; then
  echo "ERROR: Branch name '$branch' does not match naming convention."
  echo "Expected pattern: main|master|develop|release/*|hotfix/*|feat/*|feature/*|fix/*|chore/*"
  exit 1
fi
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::process::Command;

    /// Runs the `no-trailers` script exactly as git's commit-msg hook would:
    /// `sh <script> <commit-msg-file>`. Returns (accepted, combined stdout+stderr).
    fn run_no_trailers(message: &str) -> (bool, String) {
        let mut file = tempfile::NamedTempFile::new().unwrap();
        file.write_all(message.as_bytes()).unwrap();
        file.flush().unwrap();

        let output = Command::new("sh")
            .arg("-c")
            .arg(NO_TRAILERS)
            .arg("no-trailers")
            .arg(file.path())
            .output()
            .expect("failed to run no-trailers script");

        let mut combined = String::from_utf8_lossy(&output.stdout).to_string();
        combined.push_str(&String::from_utf8_lossy(&output.stderr));
        (output.status.success(), combined)
    }

    #[test]
    fn no_trailers_is_registered_as_commit_msg_builtin() {
        let builtin = get("no-trailers").unwrap();
        assert_eq!(builtin.hook, "commit-msg");
        assert!(!builtin.description.is_empty());
        assert!(builtin.script.starts_with("#!/bin/sh"));
    }

    #[test]
    fn no_trailers_script_matches_every_known_vendor() {
        for address in AI_VENDOR_NOREPLY_ADDRESSES {
            assert!(
                NO_TRAILERS.contains(address),
                "NO_TRAILERS vendor pattern is missing '{address}' from AI_VENDOR_NOREPLY_ADDRESSES"
            );
        }
    }

    #[test]
    fn rejects_co_authored_by_anthropic_noreply() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n",
        );
        assert!(!accepted);
        assert!(output.contains("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"));
        assert!(
            output.contains('3'),
            "expected the line number in: {output}"
        );
    }

    #[test]
    fn rejects_assisted_by_anthropic_noreply() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nAssisted-By: Claude Opus 5 <noreply@anthropic.com>\n",
        );
        assert!(!accepted);
        assert!(output.contains("Assisted-By: Claude Opus 5 <noreply@anthropic.com>"));
    }

    #[test]
    fn rejects_ai_assisted_by_anthropic_noreply() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nAI-Assisted-By: Claude Opus 5 <noreply@anthropic.com>\n",
        );
        assert!(!accepted);
        assert!(output.contains("AI-Assisted-By: Claude Opus 5 <noreply@anthropic.com>"));
    }

    #[test]
    fn rejects_claude_session_line() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nClaude-Session: https://claude.ai/code/session_abc123\n",
        );
        assert!(!accepted);
        assert!(output.contains("Claude-Session: https://claude.ai/code/session_abc123"));
    }

    #[test]
    fn rejects_generated_with_line() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n",
        );
        assert!(!accepted);
        assert!(output.contains("Generated with [Claude Code]"));
    }

    #[test]
    fn accepts_human_co_authored_by() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nCo-Authored-By: Jane Doe <jane@example.com>\n",
        );
        assert!(accepted, "human co-authorship must be accepted: {output}");
        assert!(output.is_empty());
    }

    #[test]
    fn accepts_clean_message_silently() {
        let (accepted, output) =
            run_no_trailers("fix: adjust retry backoff\n\nNo trailers here at all.\n");
        assert!(accepted);
        assert!(output.is_empty());
    }

    #[test]
    fn case_insensitive_co_authored_by_is_rejected() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nco-authored-by: claude opus 5 <noreply@anthropic.com>\n",
        );
        assert!(!accepted);
        assert!(output.to_lowercase().contains("noreply@anthropic.com"));
    }

    #[test]
    fn trailer_in_middle_of_body_is_rejected() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n\nMore context added after the trailer.\n",
        );
        assert!(!accepted);
        assert!(output.contains("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"));
    }

    #[test]
    fn rejects_real_fixture_self_update_docs_commit() {
        let message = "docs: Add self-update documentation and update feature summary\n\n\
Document the automatic version check and self-update mechanism shipped in\n\
commit 6a48cc2. Includes:\n\
- Self-update section in Installation guide\n\
- GITKIT_NO_UPDATE_CHECK environment variable to opt out\n\
- Cargo-managed install handling (points to cargo install --force)\n\
- Binary-in-place update behavior\n\n\
Also update index.md to reflect current capabilities:\n\
- Agent lock now blocks commits and/or pushes (not just commits)\n\
- Add self-update to the feature list\n\
- Update documentation guide to mention automatic self-updates\n\n\
Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n";
        let (accepted, output) = run_no_trailers(message);
        assert!(!accepted);
        assert!(output.contains("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"));
    }

    #[test]
    fn rejects_real_fixture_lock_docs_commit() {
        let message = "docs(lock): Document push-blocking with --push and --all flags\n\n\
Add comprehensive documentation for push-blocking feature shipped in\n\
commit 6a48cc2. Includes:\n\
- Examples for --push and --all flags\n\
- Explanation of pre-push hook mechanics\n\
- Per-operation status output (commit/push locked separately)\n\
- Updated bypass documentation for git push --no-verify\n\n\
Previously, docs/lock.md only covered commit-blocking, leaving half the\n\
feature undocumented.\n\n\
Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n\
Claude-Session: https://claude.ai/code/session_0171qBHfy9pJJMMchisoq1nN\n";
        let (accepted, output) = run_no_trailers(message);
        assert!(!accepted);
        assert!(output.contains("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"));
        assert!(output
            .contains("Claude-Session: https://claude.ai/code/session_0171qBHfy9pJJMMchisoq1nN"));
    }
}
