pub(crate) struct Builtin {
    pub name: &'static str,
    pub hook: &'static str,
    pub description: &'static str,
    pub script: &'static str,
}

pub(crate) const ALL: &[Builtin] = &[
    Builtin {
        name: "conventional-commits",
        hook: "commit-msg",
        description: "Validates Conventional Commits format",
        script: CONVENTIONAL_COMMITS,
    },
    Builtin {
        name: "no-trailers",
        hook: "commit-msg",
        description: "Rejects commit messages carrying AI attribution trailers",
        script: NO_TRAILERS,
    },
    Builtin {
        name: "no-secrets",
        hook: "pre-commit",
        description: "Detects common secret patterns in staged changes",
        script: NO_SECRETS,
    },
    Builtin {
        name: "branch-naming",
        hook: "pre-commit",
        description: "Validates branch name matches convention",
        script: BRANCH_NAMING,
    },
    Builtin {
        name: "no-invisibles",
        hook: "pre-commit",
        description: "Rejects added lines carrying invisible Unicode characters",
        script: NO_INVISIBLES,
    },
    Builtin {
        name: "no-body",
        hook: "commit-msg",
        description: "Rejects a commit message that has a body",
        script: NO_BODY,
    },
];

pub(crate) fn get(name: &str) -> Option<&'static Builtin> {
    ALL.iter().find(|b| b.name == name)
}

/// The four message shapes git writes itself, never a human: `git revert`,
/// a `git merge` conflict message, `git commit --fixup` and `git commit
/// --squash`. A convention meant for hand-authored subjects must not reject
/// them. Shared by every commit-msg builtin that needs the exemption
/// (currently `conventional-commits` and `no-body`) so the set can only be
/// defined once — a builtin that needs it embeds this macro rather than
/// copying the `case` block.
macro_rules! auto_generated_message_exemption {
    () => {
        r#"case "$subject" in
  'Revert "'*) exit 0 ;;
  'Merge '*) exit 0 ;;
  'fixup! '*) exit 0 ;;
  'squash! '*) exit 0 ;;
esac
"#
    };
}

const CONVENTIONAL_COMMITS: &str = concat!(
    r#"#!/bin/sh
# gitkit-builtin: conventional-commits
# Validates only the first line (the subject). grep matches line-by-line, so
# without this the whole message would pass if ANY line looked conventional,
# not just the first.
subject=$(sed -n '1p' "$1")

# Revert, merge, fixup! and squash! commits are auto-generated, not
# hand-authored, so this convention -- meant for human-written subjects --
# does not apply to them.
"#,
    auto_generated_message_exemption!(),
    r#"
pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?!?: .{1,}'
if ! echo "$subject" | grep -qE "$pattern"; then
  echo "ERROR: Commit message does not follow Conventional Commits format."
  echo "Expected: <type>(<scope>): <description>"
  echo "Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
  echo "Breaking change: <type>(<scope>)!: <description>"
  exit 1
fi
"#
);

/// Known AI vendor no-reply addresses that mark an autogenerated attribution
/// trailer (e.g. `Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>`).
/// Add a vendor here, and keep the `vendor_addresses` pattern inside
/// `NO_TRAILERS` in sync — `no_trailers_script_matches_every_known_vendor`
/// in the tests below enforces that. Only read by tests, hence the allow.
#[allow(dead_code)]
pub(crate) const AI_VENDOR_NOREPLY_ADDRESSES: &[&str] = &["noreply@anthropic.com"];

const NO_TRAILERS: &str = r#"#!/bin/sh
# gitkit-builtin: no-trailers
# Rejects commit messages carrying AI attribution trailers: a Co-Authored-By,
# Assisted-By or AI-Assisted-By line naming a known AI vendor no-reply
# address, a Claude-Session line, or a "Generated with" line. Genuine human
# Co-Authored-By trailers are left alone.
msg_file="$1"
vendor_addresses='noreply@anthropic\.com'
pattern="^(Co-Authored-By|Assisted-By|AI-Assisted-By):.*(${vendor_addresses})|^Claude-Session:|Generated with"

matches=$(grep -niE "$pattern" "$msg_file")
if [ -n "$matches" ]; then
  echo "ERROR: commit message contains an AI attribution trailer:"
  echo "$matches" | sed 's/^/  /'
  echo ""
  echo "Remove the line(s) above and commit again."
  echo "Human co-authorship is fine: only known AI vendor no-reply addresses (e.g. noreply@anthropic.com) are rejected."
  exit 1
fi
"#;

const NO_SECRETS: &str = r#"#!/bin/sh
# gitkit-builtin: no-secrets
# Detects common secret patterns. Not exhaustive — use dedicated tools for production.
patterns='(AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{35}|ghp_[0-9A-Za-z]{36}|sk-[0-9A-Za-z]{48}|password\s*=\s*["'"'"'][^"'"'"']{8,})'
if git diff --cached --diff-filter=ACM | grep -qE "$patterns"; then
  echo "ERROR: Possible secret detected in staged changes."
  echo "Review your changes and remove any credentials before committing."
  exit 1
fi
"#;

const BRANCH_NAMING: &str = r#"#!/bin/sh
# gitkit-builtin: branch-naming
branch=$(git symbolic-ref --short HEAD)
pattern='^(main|master|develop|release/.+|hotfix/.+|feat/.+|feature/.+|fix/.+|chore/.+)$'
if ! echo "$branch" | grep -qE "$pattern"; then
  echo "ERROR: Branch name '$branch' does not match naming convention."
  echo "Expected pattern: main|master|develop|release/*|hotfix/*|feat/*|feature/*|fix/*|chore/*"
  exit 1
fi
"#;

// Unlike the other builtins above, this one execs back into gitkit rather
// than doing its own detection in `sh`. Finding invisible characters by file,
// line, column and codepoint needs real Unicode-aware text handling (decoding
// UTF-8, counting scalar values, distinguishing a leading BOM from one added
// mid-file) that POSIX sh's text tools cannot do reliably or portably. The
// actual scan lives in `no_invisibles.rs`, is pure Rust std library, and is
// unit-tested directly there.
const NO_INVISIBLES: &str = r#"#!/bin/sh
# gitkit-builtin: no-invisibles
# Rejects added lines carrying invisible Unicode: zero-width characters,
# bidi controls (also the "Trojan Source" vector) and Unicode tag
# characters. Only lines this commit adds are scanned, not the whole file —
# see docs/hooks.md. Delegates to gitkit itself for the actual scan.
exec gitkit hooks scan-invisibles
"#;

const NO_BODY: &str = concat!(
    r#"#!/bin/sh
# gitkit-builtin: no-body
# Rejects a commit message with a body. A conforming message is one line,
# with any number of trailing newlines. The only body this hook allows is a
# blank line followed by a BREAKING CHANGE:/BREAKING-CHANGE: footer (case
# matters, per the Conventional Commits spec) with nothing before or after
# it besides the footer's own wrapped continuation lines. Revert, merge,
# fixup! and squash! commits are auto-generated, not hand-authored, and are
# always accepted.
msg_file="$1"
subject=$(sed -n '1p' "$msg_file")

reject() {
  echo "ERROR: commit message has a body; this hook only allows a single-line subject."
  echo ""
  echo "A bulleted restatement of the diff doesn't belong here -- 'git show' already tells that story better. If the change needs explaining, put the why in the pull request description, not the commit body."
  echo ""
  echo "The only exception is a breaking change, and either form is fine:"
  echo "  1) mark it in the subject:  feat(api)!: drop the v1 endpoint"
  echo "  2) or state it in a footer, and nothing else in the body:"
  echo "       BREAKING CHANGE: <what breaks, and what to do about it>"
  echo "     (a blank line before the footer; BREAKING-CHANGE: also works)"
  exit 1
}

"#,
    auto_generated_message_exemption!(),
    r#"
msg=$(cat "$msg_file")
total=$(printf '%s\n' "$msg" | wc -l)
if [ "$total" -le 1 ]; then
  exit 0
fi

second_line=$(printf '%s\n' "$msg" | sed -n '2p')
if [ -n "$second_line" ]; then
  reject
fi

third_line=$(printf '%s\n' "$msg" | sed -n '3p')
if ! printf '%s\n' "$third_line" | grep -qE '^(BREAKING CHANGE|BREAKING-CHANGE): .+'; then
  reject
fi

seen_blank=0
i=4
while [ "$i" -le "$total" ]; do
  line=$(printf '%s\n' "$msg" | sed -n "${i}p")
  if [ -z "$line" ]; then
    seen_blank=1
  elif [ "$seen_blank" -eq 1 ]; then
    reject
  fi
  i=$((i + 1))
done
"#
);

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::process::Command;

    /// Runs the `no-trailers` script exactly as git's commit-msg hook would:
    /// `sh <script> <commit-msg-file>`. Returns (accepted, combined stdout+stderr).
    fn run_no_trailers(message: &str) -> (bool, String) {
        let mut file = tempfile::NamedTempFile::new().unwrap();
        file.write_all(message.as_bytes()).unwrap();
        file.flush().unwrap();

        let output = Command::new("sh")
            .arg("-c")
            .arg(NO_TRAILERS)
            .arg("no-trailers")
            .arg(file.path())
            .output()
            .expect("failed to run no-trailers script");

        let mut combined = String::from_utf8_lossy(&output.stdout).to_string();
        combined.push_str(&String::from_utf8_lossy(&output.stderr));
        (output.status.success(), combined)
    }

    /// Runs a commit-msg builtin script exactly as git would: `sh <script>
    /// <commit-msg-file>`. Returns (accepted, combined stdout+stderr).
    fn run_commit_msg_script(script: &str, message: &str) -> (bool, String) {
        let mut file = tempfile::NamedTempFile::new().unwrap();
        file.write_all(message.as_bytes()).unwrap();
        file.flush().unwrap();

        let output = Command::new("sh")
            .arg("-c")
            .arg(script)
            .arg("script")
            .arg(file.path())
            .output()
            .expect("failed to run commit-msg script");

        let mut combined = String::from_utf8_lossy(&output.stdout).to_string();
        combined.push_str(&String::from_utf8_lossy(&output.stderr));
        (output.status.success(), combined)
    }

    fn run_conventional_commits(message: &str) -> (bool, String) {
        run_commit_msg_script(CONVENTIONAL_COMMITS, message)
    }

    fn run_no_body(message: &str) -> (bool, String) {
        run_commit_msg_script(NO_BODY, message)
    }

    #[test]
    fn conventional_commits_accepts_bang_breaking_change_no_scope() {
        let (accepted, output) = run_conventional_commits("feat!: drop v1\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn conventional_commits_accepts_bang_breaking_change_with_scope() {
        let (accepted, output) = run_conventional_commits("feat(api)!: drop v1\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn conventional_commits_rejects_conventional_subject_only_on_a_later_line() {
        // Regression test: grep matches line-by-line, so without anchoring to
        // the first line, a "wip" subject followed by a conventional-looking
        // third line used to pass.
        let (accepted, output) = run_conventional_commits("wip\n\nfix: something\n");
        assert!(
            !accepted,
            "a conventional-looking line beyond the subject must not pass: {output}"
        );
    }

    #[test]
    fn conventional_commits_still_accepts_plain_conventional_subject() {
        let (accepted, output) = run_conventional_commits("feat(x): add thing\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn conventional_commits_still_rejects_non_conventional_subject() {
        let (accepted, _) = run_conventional_commits("just a message\n");
        assert!(!accepted);
    }

    #[test]
    fn conventional_commits_rejects_hand_written_non_conventional_subject() {
        let (accepted, _) = run_conventional_commits("arreglé cosas\n");
        assert!(!accepted);
    }

    #[test]
    fn conventional_commits_rejects_invented_type() {
        let (accepted, _) = run_conventional_commits("GK-A: add thing\n");
        assert!(!accepted);
    }

    #[test]
    fn conventional_commits_accepts_breaking_change_footer_form() {
        let (accepted, output) = run_conventional_commits(
            "feat(api): drop v1\n\nBREAKING CHANGE: the v1 endpoint is gone\n",
        );
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn conventional_commits_accepts_revert_commit() {
        let (accepted, output) = run_conventional_commits(
            "Revert \"feat(x): add thing\"\n\nThis reverts commit abc123.\n",
        );
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn conventional_commits_accepts_merge_commit() {
        let (accepted, output) = run_conventional_commits("Merge branch 'develop' into main\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn conventional_commits_accepts_fixup_commit() {
        let (accepted, output) = run_conventional_commits("fixup! feat(x): add thing\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn conventional_commits_accepts_squash_commit() {
        let (accepted, output) = run_conventional_commits("squash! feat(x): add thing\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn conventional_commits_and_no_body_share_the_identical_exemption_set() {
        let exemption = auto_generated_message_exemption!();
        assert!(
            CONVENTIONAL_COMMITS.contains(exemption),
            "conventional-commits must embed the exact shared exemption block"
        );
        assert!(
            NO_BODY.contains(exemption),
            "no-body must embed the exact shared exemption block"
        );
    }

    #[test]
    fn no_body_is_registered_as_commit_msg_builtin() {
        let builtin = get("no-body").unwrap();
        assert_eq!(builtin.hook, "commit-msg");
        assert!(!builtin.description.is_empty());
        assert!(builtin.script.starts_with("#!/bin/sh"));
    }

    #[test]
    fn no_body_accepts_one_line_message() {
        let (accepted, output) = run_no_body("fix: correct the slug\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_body_rejects_bulleted_diff_inventory_and_names_both_breaking_change_forms() {
        // Verbatim fixture from the WHY section of the spec: a correct
        // conventional subject followed by a bulleted restatement of the diff.
        let message = "feat(spell): add texforge spell CLI for managing personal dictionary\n\n\
- Added spell add/list/remove subcommands\n\
- Added --global flag\n\
- Updated load_project_whitelist to union both scopes\n\
- Added 8 tests\n\
- Updated docs/cli-reference.md\n";
        let (accepted, output) = run_no_body(message);
        assert!(!accepted, "a bulleted diff inventory must be rejected");
        assert!(
            output.contains("!:"),
            "rejection must name the `!` breaking-change form: {output}"
        );
        assert!(
            output.contains("BREAKING CHANGE:"),
            "rejection must name the footer breaking-change form: {output}"
        );
    }

    #[test]
    fn no_body_accepts_breaking_change_footer() {
        let (accepted, output) =
            run_no_body("feat(api)!: drop v1\n\nBREAKING CHANGE: the v1 endpoint is gone\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_body_accepts_hyphenated_breaking_change_footer() {
        let (accepted, output) =
            run_no_body("feat(api)!: drop v1\n\nBREAKING-CHANGE: the v1 endpoint is gone\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_body_accepts_breaking_change_footer_wrapped_onto_continuation_line() {
        let (accepted, output) = run_no_body(
            "feat(api)!: drop v1\n\nBREAKING CHANGE: this is a long description that\n  continues on the next line\n",
        );
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_body_rejects_lowercase_breaking_change_footer() {
        let (accepted, _) =
            run_no_body("feat(api)!: drop v1\n\nbreaking change: the v1 endpoint is gone\n");
        assert!(
            !accepted,
            "lowercase breaking change is not a footer per the spec"
        );
    }

    #[test]
    fn no_body_rejects_breaking_change_footer_followed_by_bullet_list() {
        let message = "feat(api)!: drop v1\n\nBREAKING CHANGE: the v1 endpoint is gone\n\n- old clients must migrate\n- see migration guide\n";
        let (accepted, _) = run_no_body(message);
        assert!(
            !accepted,
            "content after the footer's blank-line separator must be rejected"
        );
    }

    #[test]
    fn no_body_rejects_paragraph_followed_by_breaking_change_footer() {
        let message = "feat(api)!: drop v1\n\nThis is some explanation paragraph.\n\nBREAKING CHANGE: the v1 endpoint is gone\n";
        let (accepted, _) = run_no_body(message);
        assert!(
            !accepted,
            "a paragraph before the footer disqualifies the exception"
        );
    }

    #[test]
    fn no_body_accepts_revert_commit() {
        let (accepted, output) =
            run_no_body("Revert \"fix: something\"\n\nThis reverts commit abc123.\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_body_accepts_merge_commit() {
        let (accepted, output) = run_no_body("Merge branch 'develop'\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_body_accepts_fixup_commit() {
        let (accepted, output) = run_no_body("fixup! fix: something\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_body_accepts_squash_commit() {
        let (accepted, output) = run_no_body("squash! fix: something\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_body_accepts_subject_with_trailing_newlines() {
        let (accepted, output) = run_no_body("fix: correct the slug\n\n\n");
        assert!(accepted, "expected acceptance: {output}");
    }

    #[test]
    fn no_trailers_is_registered_as_commit_msg_builtin() {
        let builtin = get("no-trailers").unwrap();
        assert_eq!(builtin.hook, "commit-msg");
        assert!(!builtin.description.is_empty());
        assert!(builtin.script.starts_with("#!/bin/sh"));
    }

    #[test]
    fn no_trailers_script_matches_every_known_vendor() {
        for address in AI_VENDOR_NOREPLY_ADDRESSES {
            assert!(
                NO_TRAILERS.contains(address),
                "NO_TRAILERS vendor pattern is missing '{address}' from AI_VENDOR_NOREPLY_ADDRESSES"
            );
        }
    }

    #[test]
    fn rejects_co_authored_by_anthropic_noreply() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n",
        );
        assert!(!accepted);
        assert!(output.contains("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"));
        assert!(
            output.contains('3'),
            "expected the line number in: {output}"
        );
    }

    #[test]
    fn rejects_assisted_by_anthropic_noreply() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nAssisted-By: Claude Opus 5 <noreply@anthropic.com>\n",
        );
        assert!(!accepted);
        assert!(output.contains("Assisted-By: Claude Opus 5 <noreply@anthropic.com>"));
    }

    #[test]
    fn rejects_ai_assisted_by_anthropic_noreply() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nAI-Assisted-By: Claude Opus 5 <noreply@anthropic.com>\n",
        );
        assert!(!accepted);
        assert!(output.contains("AI-Assisted-By: Claude Opus 5 <noreply@anthropic.com>"));
    }

    #[test]
    fn rejects_claude_session_line() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nClaude-Session: https://claude.ai/code/session_abc123\n",
        );
        assert!(!accepted);
        assert!(output.contains("Claude-Session: https://claude.ai/code/session_abc123"));
    }

    #[test]
    fn rejects_generated_with_line() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n",
        );
        assert!(!accepted);
        assert!(output.contains("Generated with [Claude Code]"));
    }

    #[test]
    fn accepts_human_co_authored_by() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nCo-Authored-By: Jane Doe <jane@example.com>\n",
        );
        assert!(accepted, "human co-authorship must be accepted: {output}");
        assert!(output.is_empty());
    }

    #[test]
    fn accepts_clean_message_silently() {
        let (accepted, output) =
            run_no_trailers("fix: adjust retry backoff\n\nNo trailers here at all.\n");
        assert!(accepted);
        assert!(output.is_empty());
    }

    #[test]
    fn case_insensitive_co_authored_by_is_rejected() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nco-authored-by: claude opus 5 <noreply@anthropic.com>\n",
        );
        assert!(!accepted);
        assert!(output.to_lowercase().contains("noreply@anthropic.com"));
    }

    #[test]
    fn trailer_in_middle_of_body_is_rejected() {
        let (accepted, output) = run_no_trailers(
            "fix: adjust retry backoff\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n\nMore context added after the trailer.\n",
        );
        assert!(!accepted);
        assert!(output.contains("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"));
    }

    #[test]
    fn rejects_real_fixture_self_update_docs_commit() {
        let message = "docs: Add self-update documentation and update feature summary\n\n\
Document the automatic version check and self-update mechanism shipped in\n\
commit 6a48cc2. Includes:\n\
- Self-update section in Installation guide\n\
- GITKIT_NO_UPDATE_CHECK environment variable to opt out\n\
- Cargo-managed install handling (points to cargo install --force)\n\
- Binary-in-place update behavior\n\n\
Also update index.md to reflect current capabilities:\n\
- Agent lock now blocks commits and/or pushes (not just commits)\n\
- Add self-update to the feature list\n\
- Update documentation guide to mention automatic self-updates\n\n\
Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n";
        let (accepted, output) = run_no_trailers(message);
        assert!(!accepted);
        assert!(output.contains("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"));
    }

    #[test]
    fn no_invisibles_is_registered_as_pre_commit_builtin() {
        let builtin = get("no-invisibles").unwrap();
        assert_eq!(builtin.hook, "pre-commit");
        assert!(!builtin.description.is_empty());
        assert!(!builtin.description.to_lowercase().contains("watermark"));
        assert!(builtin.script.starts_with("#!/bin/sh"));
        assert!(builtin.script.contains("gitkit hooks scan-invisibles"));
    }

    #[test]
    fn rejects_real_fixture_lock_docs_commit() {
        let message = "docs(lock): Document push-blocking with --push and --all flags\n\n\
Add comprehensive documentation for push-blocking feature shipped in\n\
commit 6a48cc2. Includes:\n\
- Examples for --push and --all flags\n\
- Explanation of pre-push hook mechanics\n\
- Per-operation status output (commit/push locked separately)\n\
- Updated bypass documentation for git push --no-verify\n\n\
Previously, docs/lock.md only covered commit-blocking, leaving half the\n\
feature undocumented.\n\n\
Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n\
Claude-Session: https://claude.ai/code/session_0171qBHfy9pJJMMchisoq1nN\n";
        let (accepted, output) = run_no_trailers(message);
        assert!(!accepted);
        assert!(output.contains("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"));
        assert!(output
            .contains("Claude-Session: https://claude.ai/code/session_0171qBHfy9pJJMMchisoq1nN"));
    }
}
